<a href="https://colab.research.google.com/github/rookasrudzianskas/PytorchModels/blob/master/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [211]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


In [212]:
# Introduction to tensors
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [213]:
scalar.ndim

0

In [214]:
scalar.item()

7

In [215]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [216]:
vector.ndim

1

In [217]:
vector.shape

torch.Size([2])

In [218]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [219]:
MATRIX.ndim


2

In [220]:
MATRIX[0]

tensor([7, 8])

In [221]:
MATRIX.shape

torch.Size([2, 2])

In [222]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 4, 5], [5, 6, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [223]:
TENSOR.ndim


3

In [224]:
TENSOR.shape

torch.Size([1, 3, 3])

In [225]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

### RAMNDON tensors


Random tensors are important because the way many neural networks learn is that they start with tensors full of randm
numbers and then adjust those random numbers to better represent the data



In [226]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5999, 0.3332, 0.3775, 0.6070],
        [0.2233, 0.7872, 0.6315, 0.5161],
        [0.6088, 0.3847, 0.4410, 0.6305]])

In [227]:
random_tensor.ndim

2

In [228]:
random_tensor.shape

torch.Size([3, 4])

In [229]:
random_tensor.ndim

2

In [230]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color of channel RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [231]:
torch.rand(size=(3, 3))


tensor([[0.0359, 0.1480, 0.2611],
        [0.3582, 0.1730, 0.4588],
        [0.9182, 0.8411, 0.9333]])

# Zeros and ones tensor


In [232]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [233]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [234]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [235]:
ones.dtype

torch.float32

torch.float32

In [236]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
torch.__version__

'1.12.1+cu113'

In [238]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [239]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [240]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [241]:
float_32_tensor.dtype

torch.float32

In [242]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [243]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [244]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.long)
int_32_tensor

tensor([3, 6, 8])

In [245]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 72.])

In [246]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4814, 0.8690, 0.6924, 0.3781],
        [0.6134, 0.7231, 0.9655, 0.8437],
        [0.0645, 0.7105, 0.1655, 0.6707]])

In [247]:
print(some_tensor)
print(f"Data type of tensor { some_tensor.dtype }")
print(f"Shape of tensor {some_tensor.shape}")
print(f"Size of tensor {some_tensor.size()}")
print(f"Device is on: {some_tensor.device}")

tensor([[0.4814, 0.8690, 0.6924, 0.3781],
        [0.6134, 0.7231, 0.9655, 0.8437],
        [0.0645, 0.7105, 0.1655, 0.6707]])
Data type of tensor torch.float32
Shape of tensor torch.Size([3, 4])
Size of tensor torch.Size([3, 4])
Device is on: cpu


In [248]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [249]:
tensor * 10

tensor([10, 20, 30])

In [250]:
tensor

tensor([1, 2, 3])

In [251]:
tensor - 10

tensor([-9, -8, -7])

In [252]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [253]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [254]:
tensor

tensor([1, 2, 3])

In [255]:
print(tensor, "*", tensor);
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [256]:
torch.matmul(tensor, tensor)

tensor(14)

In [257]:
tensor = torch.tensor([1, 2, 3])

In [258]:

tensor

tensor([1, 2, 3])

1 * 1 + 2 * 2 + 3 * 3

In [259]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value 

CPU times: user 133 µs, sys: 16 µs, total: 149 µs
Wall time: 156 µs


tensor(14)

In [260]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 33 µs, sys: 4 µs, total: 37 µs
Wall time: 41.5 µs


tensor(14)

In [261]:
tensor @ tensor


tensor(14)

In [262]:
torch.matmul(torch.rand(13, 10), torch.rand(10, 13))

tensor([[3.4069, 2.7426, 3.3325, 2.0588, 3.4224, 3.7441, 3.1462, 4.4069, 2.2405,
         2.9634, 3.2167, 3.6734, 3.9555],
        [1.5558, 1.4171, 1.7247, 1.3980, 1.7152, 1.8954, 1.4861, 2.0041, 1.2930,
         1.6623, 2.1629, 2.2443, 2.3781],
        [2.4082, 2.1108, 2.1735, 1.8676, 1.9803, 2.6633, 2.1114, 2.5342, 1.8942,
         2.3277, 2.3374, 2.9303, 2.5656],
        [2.1258, 2.0615, 2.2089, 1.6207, 1.9172, 2.9456, 1.2627, 2.3226, 1.7172,
         1.9626, 2.1446, 2.8981, 2.3182],
        [4.0223, 3.2859, 3.6821, 2.8468, 3.3169, 4.0108, 3.4796, 5.0684, 2.3451,
         3.1764, 3.8689, 3.5471, 4.3844],
        [2.9071, 2.3871, 2.4178, 2.0213, 2.1520, 3.3502, 1.9922, 3.4170, 1.6417,
         2.5363, 2.2826, 2.5849, 2.6156],
        [1.8103, 1.7796, 1.9749, 1.0428, 1.6093, 2.5685, 1.1689, 2.0485, 1.4400,
         1.3694, 1.7091, 2.1863, 2.0633],
        [2.2054, 1.9559, 2.2699, 1.5294, 1.9934, 3.0616, 1.2424, 2.4290, 1.5751,
         2.1129, 1.9233, 2.6412, 2.1540],
        [3.2154,

In [263]:
# tensor_A.shape, tensor_B.shape

In [267]:
# tensor_B.T, tensor_B.T.shape

In [268]:
# print(f"Original shapes: {tensor_A.shape}, tensor_B = {tensor_B.shape}")
# print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
# print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match")
# output = torch.mm(tensor_A, tensor_B.T)
# print(output)
# print(f"Output shape: {output.shape}")


In [269]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [270]:
torch.min(x), x.min

(tensor(1), <function Tensor.min>)

In [271]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [272]:
x.dtype

torch.int64

In [273]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [274]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [275]:
x.argmin()

tensor(0)

In [276]:
x.argmax()

tensor(9)

In [277]:
x[9]

tensor(91)

In [278]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [279]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [280]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [281]:
z[:, 0] = 5
x, x

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [282]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([4, 9]))

In [283]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [284]:
x_reshaped.shape

torch.Size([1, 9])

In [285]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [286]:
x_reshaped.squeeze().shape

torch.Size([9])

In [287]:
print(f"Previrous tensor: {x_reshaped}")
print(f"Previrous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")

Previrous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previrous shape: torch.Size([1, 9])
New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [290]:
print(f"Previorus target: {x_squeezed}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print("New tensor", x_unsqueezed)

Previorus target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [295]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)
print(f"Original {x_original.shape}")
print(f"New :{x_permuted.shape}")


Original torch.Size([224, 224, 3])
New :torch.Size([3, 224, 224])


In [298]:
# x_original[0, 0, 0] = 754835
# x_original[0, 0, 0], x_permuted[0, 0, 0]

TypeError: ignored

In [301]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))